version : '3'

services:
  postgres:
    image: postgres:latest
  
  redis-server:
    image: redis:latest

  ngnix-proxy1:
    restart: always
    build:
      context: ./ngnix
      dockerfile: Dockerfile.dev
    ports:
      - '9900:80'

  
 